"""
Django settings for admin_panel project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables from a local .env file if present (simple loader).
# DJANGO_ENV_FILE lets management commands explicitly use the production file.
ENV_PATH = Path(os.environ.get('DJANGO_ENV_FILE', BASE_DIR / '.env'))
if ENV_PATH.exists():
    try:
        for _line in ENV_PATH.read_text(encoding='utf-8').splitlines():
            line = _line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            k, v = line.split('=', 1)
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            os.environ.setdefault(k, v)
    except Exception:
        # Ignore .env parse issues silently to avoid breaking settings
        pass

SITE_NAME = os.environ.get('SITE_NAME', 'MineraLife')
REPORTS_PASSWORD = os.environ.get('REPORTS_PASSWORD', 'change-me')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-7jpa7hp@yv8krwag6t_f64(4+z&qqsi$h(^+oc)km7*%imqo=#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# Parse ALLOWED_HOSTS from environment
ALLOWED_HOSTS_STR = os.environ.get('ALLOWED_HOSTS', '*')
if ALLOWED_HOSTS_STR == '*':
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',')]
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'               # muvaffaqiyatli kirganda qayerga olib borish
LOGOUT_REDIRECT_URL = '/accounts/login/'  # chiqgandan keyin login sahifaga qaytarish


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    "products",
    "clients",
    "orders",
    "couriers",
    "common",
    "hisobotlar",
    "api",
    "django.contrib.humanize"
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'admin_panel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "Templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'common.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'admin_panel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _database_env(*names, default=''):
    """Return the first non-empty database environment value."""
    for name in names:
        value = os.environ.get(name)
        if value not in (None, ''):
            return value
    return default


DATABASE_ENGINE = os.environ.get('DB_ENGINE', '').strip().lower()
if not DATABASE_ENGINE:
    # Backwards compatibility with the existing production environment.
    DATABASE_ENGINE = (
        'mysql'
        if os.environ.get('USE_MYSQL', 'False').lower() == 'true'
        else 'sqlite'
    )

if DATABASE_ENGINE in ('postgres', 'postgresql', 'pgsql'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _database_env('DB_NAME', 'POSTGRES_DB', 'PGDATABASE'),
            'USER': _database_env('DB_USER', 'POSTGRES_USER', 'PGUSER'),
            'PASSWORD': _database_env('DB_PASSWORD', 'POSTGRES_PASSWORD', 'PGPASSWORD'),
            'HOST': _database_env('DB_HOST', 'POSTGRES_HOST', 'PGHOST', default='127.0.0.1'),
            'PORT': _database_env('DB_PORT', 'POSTGRES_PORT', 'PGPORT', default='5432'),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
            'CONN_HEALTH_CHECKS': True,
        }
    }
elif DATABASE_ENGINE == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            # MYSQL_* aliases keep the existing production environment file
            # compatible while DB_* remains the preferred naming scheme.
            'NAME': _database_env('DB_NAME', 'MYSQL_DBNAME'),
            'USER': _database_env('DB_USER', 'MYSQL_USER'),
            'PASSWORD': _database_env('DB_PASSWORD', 'MYSQL_PASSWORD'),
            'HOST': _database_env('DB_HOST', 'MYSQL_HOST', default='localhost'),
            'PORT': _database_env('DB_PORT', 'MYSQL_PORT', default='3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }
elif DATABASE_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ValueError(
        'Unsupported DB_ENGINE. Use postgresql, mysql, or sqlite.'
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Nginx terminates HTTPS and forwards the original protocol to Gunicorn.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# External API keys
# Provide via environment variable in production
YANDEX_MAPS_API_KEY = os.environ.get('YANDEX_MAPS_API_KEY', '')

# CSRF trusted origins for production
if not DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
        if origin.strip()
    ]
