# Generated by Django 5.2.6 on 2026-05-31 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_name_client_unique_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientphonenumber',
            name='description',
        ),
    ]
