# Generated by Django 4.2.11 on 2026-07-05 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzunlik')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Aniqlik (metr)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to=settings.AUTH_USER_MODEL, verbose_name='Kuryer')),
            ],
            options={
                'verbose_name': 'Kuryer joylashuvi',
                'verbose_name_plural': 'Kuryerlar joylashuvi',
            },
        ),
    ]
