# Generated by Django 6.0.4 on 2026-05-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_order_date_status_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS order_status_payment_idx;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='order',
                    name='order_status_payment_idx',
                ),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Karta to'lov summasi", max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Naqd to'lov summasi", max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Qarz summasi', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='perechesleniya_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Perechisleniya summasi', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='F',
            field=models.DecimalField(decimal_places=2, default=18000.0, help_text='Bir dona uchun narx', max_digits=10),
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
